### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by davidportella** [Vanco/SequencePlugin#10]
I tried to use for generate the diagram, but exception is a raice

IntelliJ Idea 2016.2.5
Java 1.7
Spring Framework

`
null
java.lang.NullPointerException
    at org.intellij.sequencer.util.PsiUtil.isInClassFile(PsiUtil.java:31)
    at org.intellij.sequencer.generator.SequenceGenerator.createAttributes(SequenceGenerator.java:165)
    at org.intellij.sequencer.generator.SequenceGenerator.createMethod(SequenceGenerator.java:136)
    at org.intellij.sequencer.generator.SequenceGenerator.visitMethod(SequenceGenerator.java:76)
    at com.intellij.psi.impl.light.LightMethodBuilder.accept(LightMethodBuilder.java:318)
    at org.intellij.sequencer.generator.SequenceGenerator.generate(SequenceGenerator.java:58)
    at org.intellij.sequencer.generator.SequenceGenerator.methodCall(SequenceGenerator.java:118)
    at org.intellij.sequencer.generator.SequenceGenerator.visitCallExpression(SequenceGenerator.java:92)
    at com.intellij.psi.JavaElementVisitor.visitNewExpression(JavaElementVisitor.java:195)
    at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl.accept(PsiNewExpressionImpl.java:384)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
    at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
    at com.intellij.psi.JavaElementVisitor.visitVariable(JavaElementVisitor.java:328)
    at com.intellij.psi.JavaElementVisitor.visitLocalVariable(JavaElementVisitor.java:175)
    at org.intellij.sequencer.generator.SequenceGenerator.visitLocalVariable(SequenceGenerator.java:196)
    at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.accept(PsiLocalVariableImpl.java:284)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
    at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
    at com.intellij.psi.JavaElementVisitor.visitStatement(JavaElementVisitor.java:272)
    at com.intellij.psi.JavaElementVisitor.visitDeclarationStatement(JavaElementVisitor.java:79)
    at com.intellij.psi.impl.source.tree.java.PsiDeclarationStatementImpl.accept(PsiDeclarationStatementImpl.java:89)
    at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
    at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
    at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:67)
    at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:202)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
    at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:173)
    at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
    at com.intellij.psi.JavaElementVisitor.visitMethod(JavaElementVisitor.java:179)
    at org.intellij.sequencer.generator.SequenceGenerator.visitMethod(SequenceGenerator.java:85)
    at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:283)
    at org.intellij.sequencer.generator.SequenceGenerator.generate(SequenceGenerator.java:58)
    at org.intellij.sequencer.generator.SequenceGenerator.methodCall(SequenceGenerator.java:118)
    at org.intellij.sequencer.generator.SequenceGenerator.visitCallExpression(SequenceGenerator.java:92)
    at com.intellij.psi.JavaElementVisitor.visitMethodCallExpression(JavaElementVisitor.java:183)
    at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:142)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
    at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
    at com.intellij.psi.JavaElementVisitor.visitVariable(JavaElementVisitor.java:328)
    at com.intellij.psi.JavaElementVisitor.visitLocalVariable(JavaElementVisitor.java:175)
    at org.intellij.sequencer.generator.SequenceGenerator.visitLocalVariable(SequenceGenerator.java:196)
    at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.accept(PsiLocalVariableImpl.java:284)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
    at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
    at com.intellij.psi.JavaElementVisitor.visitStatement(JavaElementVisitor.java:272)
    at com.intellij.psi.JavaElementVisitor.visitDeclarationStatement(JavaElementVisitor.java:79)
    at com.intellij.psi.impl.source.tree.java.PsiDeclarationStatementImpl.accept(PsiDeclarationStatementImpl.java:89)
    at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
    at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
    at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:67)
    at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:202)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
    at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
    at com.intellij.psi.JavaElementVisitor.visitCatchSection(JavaElementVisitor.java:304)
    at com.intellij.psi.impl.source.tree.java.PsiCatchSectionImpl.accept(PsiCatchSectionImpl.java:196)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
    at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
    at com.intellij.psi.JavaElementVisitor.visitStatement(JavaElementVisitor.java:272)
    at com.intellij.psi.JavaElementVisitor.visitTryStatement(JavaElementVisitor.java:300)
    at com.intellij.psi.impl.source.tree.java.PsiTryStatementImpl.accept(PsiTryStatementImpl.java:164)
    at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
    at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
    at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:67)
    at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:202)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
    at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:173)
    at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
    at com.intellij.psi.JavaElementVisitor.visitMethod(JavaElementVisitor.java:179)
    at org.intellij.sequencer.generator.SequenceGenerator.visitMethod(SequenceGenerator.java:85)
    at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:283)
    at org.intellij.sequencer.generator.SequenceGenerator.generate(SequenceGenerator.java:58)
    at org.intellij.sequencer.SequencePanel.generate(SequencePanel.java:89)
    at org.intellij.sequencer.SequencePlugin$1.run(SequencePlugin.java:96)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.a(ToolWindowImpl.java:209)
    at com.intellij.openapi.wm.impl.commands.InvokeLaterCmd.run(InvokeLaterCmd.java:33)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:795)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by Vanco** [comment]
Thanks for your feedback.  Which SequenceDiagram version do you use? this may helpful for me to find the bug.

**Comment by davidportella** [comment]
The version is the 1.2.1

**Comment by Vanco** [comment]
Hi David,

Thanks for your feedback.   I make a little change. I send you the next version for a try. If you still have the issue, please send me the following information:
     a) the code block you trigger the generate, or the whole class file
     b) other you thing related info
This info may help me simulate the situation, and make test case against it.
Cheers,
-Evan Fan

On 26 Oct 2016, at 3:58 AM, David Portella <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried to use for generate the diagram, but exception is a raice

null
java.lang.NullPointerException
at org.intellij.sequencer.util.PsiUtil.isInClassFile(PsiUtil.java:31)
at org.intellij.sequencer.generator.SequenceGenerator.createAttributes(SequenceGenerator.java:165)
at org.intellij.sequencer.generator.SequenceGenerator.createMethod(SequenceGenerator.java:136)
at org.intellij.sequencer.generator.SequenceGenerator.visitMethod(SequenceGenerator.java:76)
at com.intellij.psi.impl.light.LightMethodBuilder.accept(LightMethodBuilder.java:318)
at org.intellij.sequencer.generator.SequenceGenerator.generate(SequenceGenerator.java:58)
at org.intellij.sequencer.generator.SequenceGenerator.methodCall(SequenceGenerator.java:118)
at org.intellij.sequencer.generator.SequenceGenerator.visitCallExpression(SequenceGenerator.java:92)
at com.intellij.psi.JavaElementVisitor.visitNewExpression(JavaElementVisitor.java:195)
at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl.accept(PsiNewExpressionImpl.java:384)
at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
at com.intellij.psi.JavaElementVisitor.visitVariable(JavaElementVisitor.java:328)
at com.intellij.psi.JavaElementVisitor.visitLocalVariable(JavaElementVisitor.java:175)
at org.intellij.sequencer.generator.SequenceGenerator.visitLocalVariable(SequenceGenerator.java:196)
at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.accept(PsiLocalVariableImpl.java:284)
at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
at com.intellij.psi.JavaElementVisitor.visitStatement(JavaElementVisitor.java:272)
at com.intellij.psi.JavaElementVisitor.visitDeclarationStatement(JavaElementVisitor.java:79)
at com.intellij.psi.impl.source.tree.java.PsiDeclarationStatementImpl.accept(PsiDeclarationStatementImpl.java:89)
at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:67)
at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:202)
at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:173)
at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
at com.intellij.psi.JavaElementVisitor.visitMethod(JavaElementVisitor.java:179)
at org.intellij.sequencer.generator.SequenceGenerator.visitMethod(SequenceGenerator.java:85)
at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:283)
at org.intellij.sequencer.generator.SequenceGenerator.generate(SequenceGenerator.java:58)
at org.intellij.sequencer.generator.SequenceGenerator.methodCall(SequenceGenerator.java:118)
at org.intellij.sequencer.generator.SequenceGenerator.visitCallExpression(SequenceGenerator.java:92)
at com.intellij.psi.JavaElementVisitor.visitMethodCallExpression(JavaElementVisitor.java:183)
at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:142)
at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
at com.intellij.psi.JavaElementVisitor.visitVariable(JavaElementVisitor.java:328)
at com.intellij.psi.JavaElementVisitor.visitLocalVariable(JavaElementVisitor.java:175)
at org.intellij.sequencer.generator.SequenceGenerator.visitLocalVariable(SequenceGenerator.java:196)
at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.accept(PsiLocalVariableImpl.java:284)
at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
at com.intellij.psi.JavaElementVisitor.visitStatement(JavaElementVisitor.java:272)
at com.intellij.psi.JavaElementVisitor.visitDeclarationStatement(JavaElementVisitor.java:79)
at com.intellij.psi.impl.source.tree.java.PsiDeclarationStatementImpl.accept(PsiDeclarationStatementImpl.java:89)
at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:67)
at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:202)
at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
at com.intellij.psi.JavaElementVisitor.visitCatchSection(JavaElementVisitor.java:304)
at com.intellij.psi.impl.source.tree.java.PsiCatchSectionImpl.accept(PsiCatchSectionImpl.java:196)
at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
at com.intellij.psi.JavaElementVisitor.visitStatement(JavaElementVisitor.java:272)
at com.intellij.psi.JavaElementVisitor.visitTryStatement(JavaElementVisitor.java:300)
at com.intellij.psi.impl.source.tree.java.PsiTryStatementImpl.accept(PsiTryStatementImpl.java:164)
at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:67)
at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:202)
at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:173)
at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:31)
at com.intellij.psi.JavaElementVisitor.visitMethod(JavaElementVisitor.java:179)
at org.intellij.sequencer.generator.SequenceGenerator.visitMethod(SequenceGenerator.java:85)
at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:283)
at org.intellij.sequencer.generator.SequenceGenerator.generate(SequenceGenerator.java:58)
at org.intellij.sequencer.SequencePanel.generate(SequencePanel.java:89)
at org.intellij.sequencer.SequencePlugin$1.run(SequencePlugin.java:96)
at com.intellij.openapi.wm.impl.ToolWindowImpl.a(ToolWindowImpl.java:209)
at com.intellij.openapi.wm.impl.commands.InvokeLaterCmd.run(InvokeLaterCmd.java:33)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:795)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
