### ISSUE TITLE
The global search function cannot be used after exporting pictures

### ISSUE THREAD

**Issue by MoonightsZ** [Vanco/SequencePlugin#104]
The global search function cannot be used after exporting pictures.
导出图片后无法使用全局搜索功能.
After restarting idea, the global search returns to normal.
重启IDEA后,全局搜索恢复正常.

[ CTRL + F , CTRL + SHIFT + F ]

plugin version: 2.1.2
idea version: 2021.1.3

**Comment by MoonightsZ** [comment]
version 2.1.2

**Comment by Vanco** [comment]
This is caused by **IDEA core** exception in idea version 2021.1.3.  Please upgrade to later version, the issue will gone.

I tested with version 2021.2.2, no issue found.

The original exception info: 

```
Exception in **IDEA core**.

java.lang.NullPointerException
	at com.intellij.ide.HelpTooltip.deriveDescriptionFont(HelpTooltip.java:577)
	at com.intellij.ide.HelpTooltip.createTipPanel(HelpTooltip.java:435)
	at com.intellij.ide.HelpTooltip.initPopupBuilder(HelpTooltip.java:372)
	at com.intellij.ide.HelpTooltip.installImpl(HelpTooltip.java:339)
	at com.intellij.ide.HelpTooltip.installOn(HelpTooltip.java:327)
	at com.intellij.openapi.actionSystem.impl.ActionButton.updateToolTipText(ActionButton.java:385)
	at com.intellij.openapi.actionSystem.impl.ActionButton.update(ActionButton.java:282)
	at com.intellij.find.SearchTextArea.updateExtraActions(SearchTextArea.java:295)
	at com.intellij.find.SearchReplaceComponent.updateActions(SearchReplaceComponent.java:473)
	at com.intellij.find.SearchReplaceComponent.update(SearchReplaceComponent.java:456)
	at com.intellij.find.SearchReplaceComponent.<init>(SearchReplaceComponent.java:259)
	at com.intellij.find.SearchReplaceComponent$Builder.build(SearchReplaceComponent.java:796)
	at com.intellij.find.EditorSearchSession.<init>(EditorSearchSession.java:123)
	at com.intellij.find.EditorSearchSession.start(EditorSearchSession.java:265)
	at com.intellij.openapi.editor.actions.IncrementalFindAction$Handler.doExecute(IncrementalFindAction.java:66)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:52)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:199)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:89)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:98)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:73)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:68)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:616)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:676)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:675)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:626)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:486)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:481)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:232)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:889)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:833)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
