### ISSUE TITLE
Error in IJ v15 when exporting a sequence diagram

### ISSUE THREAD

**Issue by xsaycocie** [Vanco/SequencePlugin#14]
Sequence Diagram Version 1.2.2.

Get the following error when trying to export a sequence diagram:

com.intellij.util.ui.UIUtil.getSystemLookAndFeelClassName()Ljava/lang/String;
java.lang.NoSuchMethodError: com.intellij.util.ui.UIUtil.getSystemLookAndFeelClassName()Ljava/lang/String;
	at org.intellij.sequencer.diagram.Display.saveImageToFile(Display.java:194)
	at org.intellij.sequencer.SequencePanel$ExportAction.actionPerformed(SequencePanel.java:186)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:125)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:299)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Is there a version of SD where export works with IJ 15?

**Comment by Vanco** [comment]
I test the SequenceDiagram v1.2.2 with the IntelliJ IDEA 15.0.2, it works properly.

**Comment by xsaycocie** [comment]
Are you using IJ on Windows or OSX?  I am using IJ on OSX Sierra.

**Comment by Vanco** [comment]
I am using IJ on OSX Sierra too.

**Comment by xsaycocie** [comment]
I downloaded your code and this line in Display.java is commented out (line 194):

`//            String systemLookAndFeelClassName = UIUtil.getSystemLookAndFeelClassName();`

The version that IJ downloads and the 1.2.2 jar in the releases page (https://github.com/Vanco/SequencePlugin/releases) must have a version of Display.java that still has that line in it as you can see in the stack trace I originally posted.  The last version I could get the export image to work in was 1.2.

**Comment by Vanco** [comment]
I see.  Thank you for your detail information.  I will fix it in next release.

**Comment by Vanco** [comment]
I will fix it in next release.

You can use attached pre-release for a try. It fix the issue.

Thanks.
-Van Fan
