### ISSUE TITLE
Search Functionality crashes after Sequence Diagram

### ISSUE THREAD

**Issue by Ademord** [Vanco/SequencePlugin#146]
How to reproduce 100% of the time
1. ✅ use cmd+f to search/find some string in file or in project (validate search works)
2. use sequence diagram
3. ✅ search still works
4. **save diagram as png in some folder**
5. ✅ search still works if we dont change file
6. **switch to a different file**
7. ❌ search doesnt work anymore

- Error message below.
- After this the IDE **also** becomes sometimes unclickable / unresponsive.

Has anyone experienced this or know the fix?

![image](https://user-images.githubusercontent.com/4501464/203342026-5d6a7b2e-749d-4fe7-b822-9b113f4db018.png)

**Comment by Vanco** [comment]
What is the crash error message?

**Comment by Ademord** [comment]
Exception in Studio Core

```
java.lang.NullPointerException
	at com.intellij.ide.HelpTooltip.deriveDescriptionFont(HelpTooltip.java:577)
	at com.intellij.ide.HelpTooltip.createTipPanel(HelpTooltip.java:435)
	at com.intellij.ide.HelpTooltip.initPopupBuilder(HelpTooltip.java:372)
	at com.intellij.ide.HelpTooltip.installImpl(HelpTooltip.java:339)
	at com.intellij.ide.HelpTooltip.installOn(HelpTooltip.java:330)
	at com.intellij.openapi.actionSystem.impl.ActionButton.updateToolTipText(ActionButton.java:385)
	at com.intellij.openapi.actionSystem.impl.ActionButton.update(ActionButton.java:282)
	at com.intellij.openapi.actionSystem.impl.ActionButton.addNotify(ActionButton.java:276)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at com.intellij.ui.JBSplitter.addNotify(JBSplitter.java:111)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at com.intellij.ui.JBSplitter.addNotify(JBSplitter.java:111)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at com.intellij.ui.tabs.impl.JBTabsImpl.addImpl(JBTabsImpl.java:2362)
	at java.desktop/java.awt.Container.add(Container.java:436)
	at com.intellij.ui.tabs.impl.JBTabsImpl.updateContainer(JBTabsImpl.java:2336)
	at com.intellij.ui.tabs.impl.JBTabsImpl.executeSelectionChange(JBTabsImpl.java:1258)
	at com.intellij.ui.tabs.impl.JBTabsImpl$9.run(JBTabsImpl.java:1217)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.lambda$new$1(EditorTabbedContainer.java:110)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.lambda$new$2(EditorTabbedContainer.java:108)
	at com.intellij.ui.tabs.impl.JBTabsImpl._setSelected(JBTabsImpl.java:1213)
	at com.intellij.ui.tabs.impl.JBTabsImpl.select(JBTabsImpl.java:1203)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$EditorTabs.select(EditorTabbedContainer.java:696)
	at com.intellij.ui.tabs.impl.TabLabel$1.mousePressed(TabLabel.java:89)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6649)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	```
	
	i have to correct my steps to reproduce above, i had to save an image.

**Comment by Vanco** [comment]
Acording to your feedback, ` Studio Core` thorw the exception, nothing about SequenceDiagram.   I tried on `Android Studio Dolphin | 2021.3.1 Patch 1`  on windows, no issue found.   Maybe you can try other version AndroidStudio see what happen.

**Comment by Ademord** [comment]
Ehm, yes Studio Core seems to be the base layer of what Android Studio is.. so something from the plugin interfered with "Core", from my understanding.
[...]
After updating, I can confirm that the bug has not shown up. I will come back in case it happens again 👍🏻  Thank you!

<img width="580" alt="image" src="https://user-images.githubusercontent.com/4501464/203552939-fa0c3bef-7e88-4232-b5c0-61301a855d39.png">
