### ISSUE TITLE
After plugin update to 2.1a2, I have java.lang.IndexOutOfBoundsException.

### ISSUE THREAD

**Issue by raboserg** [Vanco/SequencePlugin#81]
After plugin update to 2.1a2, I have that problem.

IntelliJ IDEA 2021.1 (Community Edition)
Build #IC-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-49-generic
Current Desktop: ubuntu:GNOME

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.intellij.sequencer.generator.MethodDescription.equals(MethodDescription.java:87)
	at org.intellij.sequencer.generator.CallStack.isRecursive(CallStack.java:30)
	at org.intellij.sequencer.generator.SequenceGenerator.makeMethodCallExceptCurrentStackIsRecursive(SequenceGenerator.java:300)
	at org.intellij.sequencer.generator.SequenceGenerator.visitLambdaExpression(SequenceGenerator.java:291)
	at com.intellij.psi.impl.source.tree.java.PsiLambdaExpressionImpl.accept(PsiLambdaExpressionImpl.java:137)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
	at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:91)
	at com.intellij.psi.JavaElementVisitor.visitExpressionList(JavaElementVisitor.java:96)
	at com.intellij.psi.impl.source.tree.java.PsiExpressionListImpl.accept(PsiExpressionListImpl.java:159)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
	at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:91)
	at com.intellij.psi.JavaElementVisitor.visitExpression(JavaElementVisitor.java:92)
	at com.intellij.psi.JavaElementVisitor.visitCallExpression(JavaElementVisitor.java:176)
	at org.intellij.sequencer.generator.SequenceGenerator.visitCallExpression(SequenceGenerator.java:116)
	at com.intellij.psi.JavaElementVisitor.visitMethodCallExpression(JavaElementVisitor.java:172)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:125)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
	at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:91)
	at com.intellij.psi.JavaElementVisitor.visitVariable(JavaElementVisitor.java:332)
	at com.intellij.psi.JavaElementVisitor.visitLocalVariable(JavaElementVisitor.java:164)
	at org.intellij.sequencer.generator.SequenceGenerator.visitLocalVariable(SequenceGenerator.java:251)
	at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.accept(PsiLocalVariableImpl.java:279)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
	at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:91)
	at com.intellij.psi.JavaElementVisitor.visitStatement(JavaElementVisitor.java:272)
	at com.intellij.psi.JavaElementVisitor.visitDeclarationStatement(JavaElementVisitor.java:68)
	at com.intellij.psi.impl.source.tree.java.PsiDeclarationStatementImpl.accept(PsiDeclarationStatementImpl.java:106)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:104)
	at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:91)
	at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:56)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:212)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:113)
	at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:91)
	at com.intellij.psi.JavaElementVisitor.visitMethod(JavaElementVisitor.java:168)
	at org.intellij.sequencer.generator.SequenceGenerator.visitMethod(SequenceGenerator.java:97)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:284)
	at org.intellij.sequencer.generator.SequenceGenerator.generate(SequenceGenerator.java:68)
	at org.intellij.sequencer.generator.SequenceGenerator.methodCall(SequenceGenerator.java:177)
	at org.intellij.sequencer.generator.SequenceGenerator.visitCallExpression(SequenceGenerator.java:132)
	at com.intellij.psi.JavaElementVisitor.visitMethodCallExpression(JavaElementVisitor.java:172)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:125)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
	at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:91)
	at com.intellij.psi.JavaElementVisitor.visitExpressionList(JavaElementVisitor.java:96)
	at com.intellij.psi.impl.source.tree.java.PsiExpressionListImpl.accept(PsiExpressionListImpl.java:159)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
	at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:91)
	at com.intellij.psi.JavaElementVisitor.visitExpression(JavaElementVisitor.java:92)
	at com.intellij.psi.JavaElementVisitor.visitCallExpression(JavaElementVisitor.java:176)
	at org.intellij.sequencer.generator.SequenceGenerator.visitCallExpression(SequenceGenerator.java:120)
	at com.intellij.psi.JavaElementVisitor.visitMethodCallExpression(JavaElementVisitor.java:172)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:125)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
	at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:91)
	at com.intellij.psi.JavaElementVisitor.visitStatement(JavaElementVisitor.java:272)
	at com.intellij.psi.JavaElementVisitor.visitExpressionStatement(JavaElementVisitor.java:104)
	at com.intellij.psi.impl.source.tree.java.PsiExpressionStatementImpl.accept(PsiExpressionStatementImpl.java:78)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:104)
	at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:91)
	at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:56)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:212)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:113)
	at org.intellij.sequencer.generator.SequenceGenerator.visitElement(SequenceGenerator.java:91)
	at com.intellij.psi.JavaElementVisitor.visitMethod(JavaElementVisitor.java:168)
	at org.intellij.sequencer.generator.SequenceGenerator.visitMethod(SequenceGenerator.java:97)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:284)
	at org.intellij.sequencer.generator.SequenceGenerator.generate(SequenceGenerator.java:68)
	at org.intellij.sequencer.generator.SequenceGenerator.generate(SequenceGenerator.java:33)
	at org.intellij.sequencer.SequencePanel.generate(SequencePanel.java:94)
	at org.intellij.sequencer.impl.SequenceServiceImpl.lambda$showSequence$0(SequenceServiceImpl.java:47)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$activateToolWindow$1.run(ToolWindowManagerImpl.kt:632)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by samuelhoenle** [comment]
I have the same issue:

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-49-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1892M
Cores: 8
Kotlin: 211-1.4.32-release-IJ6693.72
Current Desktop: KDE

**Comment by raboserg** [comment]
Updated plugin to version 2.1.a3.
Issue is fix.
Thank you.
