### ISSUE TITLE
Option Sequence Diagram don't enable in Tools menu

### ISSUE THREAD

**Issue by otaviosgoncalves** [Vanco/SequencePlugin#86]
I installed the version 2.1.a4 of the plugin SequenceDiagram in intellij 2021.1.1 Build IU-211.7142.45

When I tried to generate a diagram from kotlin source:

java.lang.NullPointerException
	at org.intellij.sequencer.generator.CallStack.generate(CallStack.java:48)
	at org.intellij.sequencer.generator.CallStack.generate(CallStack.java:51)
	at org.intellij.sequencer.generator.CallStack.generate(CallStack.java:51)
	at org.intellij.sequencer.generator.CallStack.generate(CallStack.java:51)
	at org.intellij.sequencer.generator.CallStack.generate(CallStack.java:51)
	at org.intellij.sequencer.generator.CallStack.generate(CallStack.java:51)
	at org.intellij.sequencer.generator.CallStack.generate(CallStack.java:51)
	at org.intellij.sequencer.generator.CallStack.generate(CallStack.java:51)
	at org.intellij.sequencer.generator.CallStack.generate(CallStack.java:51)
	at org.intellij.sequencer.generator.CallStack.generate(CallStack.java:51)
	at org.intellij.sequencer.generator.CallStack.generate(CallStack.java:51)
	at org.intellij.sequencer.generator.CallStack.generateSequence(CallStack.java:39)
	at org.intellij.sequencer.SequencePanel.generate(SequencePanel.java:96)
	at org.intellij.sequencer.impl.SequenceServiceImpl.lambda$showSequence$0(SequenceServiceImpl.java:47)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$activateToolWindow$1.run(ToolWindowManagerImpl.kt:632)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Vanco** [comment]
try new version 2.1.2
